### ISSUE TITLE
Esta mujer es muy guapa

### ISSUE THREAD

**Issue by ZaroDev** [Sofialiles55/programming-1#1]
Pk eres tan guapa si esk no lo entiendo vas enamorando a la gente por alli, enfin espero que te vuelvas mas fea pa poder solucionarlo gracias

**Comment by Sofialiles55** [comment]
Entiendo que te pueda molestar mi genetica, lo tendre en cuenta para el futuro, que tenga un buen dia!

**Comment by Sofialiles55** [comment]
> Pk eres tan guapa si esk no lo entiendo vas enamorando a la gente por alli, enfin espero que te vuelvas mas fea pa poder solucionarlo gracias

**Comment by ZaroDev** [comment]
@Sofialiles55 UWU gracias por su consideracion pero puede confirmar lo siguiente `love = true;` ?
